### ISSUE TITLE
请问我运行了yolact_interface.py后出现这个问题要怎么解决

### ISSUE THREAD

**Issue by AndreGao08** [1812598631/Yolact-C-#1]
Traceback (most recent call last):
  File "/home/simulator/Documents/Yolact-C--main/src/python/yolact_interface.py", line 869, in eval_image
    batch = FastBaseTransform()(image_tensor.unsqueeze(0))
  File "/home/simulator/anaconda3/envs/yolact/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/simulator/Documents/Yolact-C--main/src/python/utils/augmentations.py", line 646, in forward
    img = (img - self.mean) / self.std
RuntimeError: The size of tensor a (480) must match the size of tensor b (3) at non-singleton dimension 1

**Comment by 1812598631** [comment]
输入图片需要是640-480 维度的  我是用的TUM数据集里面的图片尺寸
